DROP TYPE IF EXISTS RoleType CASCADE;
CREATE TYPE RoleType AS ENUM ('ROLE_USER','ROLE_ADMIN');
CREATE CAST (varchar AS RoleType) WITH INOUT AS IMPLICIT;
CREATE CAST (RoleType AS varchar) WITH INOUT AS IMPLICIT;