app:
    swagger-ui-version: 5.30.3

server:
    port: 8080
    servlet:
        context-path: /api/v1

spring:
    application:
        name: product-catalog
    datasource:
        url: jdbc:postgresql://localhost/
        port: 5432
        database: product_db
        username: intern
        password: 1gjAVnJ
        currentSchema: custom
    mvc:
        static-path-pattern: /swagger-ui*
    resources:
        static-locations: classpath:/webapp/

logging:
    level:
        org.springframework.security: DEBUG
