services:
  postgres:
    container_name: postgres-container
    image: postgres:12.20
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=intern
      - POSTGRES_PASSWORD=1gjAVnJ
      - POSTGRES_DB=product_db
      - POSTGRES_SCHEMA=custom
    expose:
      - 5432
    networks:
      - docker_default
    restart: unless-stopped
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  #swagger:
  #  container_name: swagger-container
  #  image: swaggerapi/swagger-ui:v5.19.0
  #  ports:
  #    - '8080:8080'
  #  networks:
  #    - docker_default
  #  restart: unless-stopped
  #  environment:
  #    SWAGGER_JSON: /app/openapi.json
  #  volumes:
  #    - ./openapi.json:/app/openapi.json

networks:
      docker_default:
        external: true
        name: docker_default
